from .base import *


SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_PRELOAD = True
CSRF_COOKIE_DOMAIN = "RAILWAY_PUBLIC_DOMAIN"
CSRF_TRUSTED_ORIGINS = [
    "https://RAILWAY_PUBLIC_DOMAIN",
]
